name         'phpops-phpbuild'
version      '0.1.1'
author       'Robin van der Vleuten'
summary      'Installs CHH/php-build through Puppet.'
description  'Installs CHH/php-build through Puppet.'
source       'https://github.com/phpops/puppet-phpbuild'
project_page 'https://github.com/phpops/puppet-phpbuild'
license      'MIT'

dependency 'puppetlabs/gcc', '>= 0.0.3'
dependency 'puppetlabs/git', '>= 0.0.3'
